server:
  port: 9982
spring:
  application:
    name: user-service2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.175.1:8848
        username: nacos
        password: nacos
        namespace: cd9d1484-80a0-4f98-b3f3-3d3347d04214