server:
  port: 10002
spring:
  application:
    name: GatewayService
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.175.1:8848
        username: nacos
        password: nacos
        namespace: public
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: userService
#          uri: http://localhost:9981
#          predicates:
#            - Path=/user/**
        - id: userService
#          uri: http://localhost:9982
          uri: lb://userService
          predicates:
            - Path=/user/**
        - id: orderService
          uri: http://localhost:9991
          predicates:
            - Path=/order/**
        - id: orderService
          uri: http://localhost:9992
          predicates:
            - Path=/order/**
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:10003
      web-context-unify: false