server:
  port: 10001
spring:
  application:
    name: GatewayService
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.175.1:8848
        username: nacos
        password: nacos
        namespace: cd9d1484-80a0-4f98-b3f3-3d3347d04214
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userService
          uri: http://localhost:9982
          predicates:
            - Path=/user/**
        - id: userService2
          uri: http://localhost:9981
          predicates:
            - Path=/user/**